### PR TITLE
fix #10

### LINKED ISSUE #10: An error occurs if I search multibyte keyword on pull_hashtag
If I search multibyte keyword on pull_hashtag, An error occurs.

ex) #毛皮

### PR DESCRIPTION
**Pull request by YuzuruS**
ref #10

### CODE REVIEW

**Comment by neerajsinghsonu** [comment]
Thank you @YuzuruS :) to pointing and fixing the issue.

**Comment by halimjr** [comment]
Hello sir,
I do not know enough coding, can you guide me how to use this code to get Instagram user's top 10 post image and link by likes/comment?
Which file and what line I have to edit?

**Comment by neerajsinghsonu** [comment]
Hi @halimjr ,

Welcome! You don't need to learn coding to use this peace of code. Just download Wamp Server or any other server which is able to run PHP language in your PC. I am taking you here via Wamp Server windows.

1. Download WAMP Server
2. Download Zip file from Git source
3. Install Wamp Server
4. Go to root folder of wamp 'Your System Drive://wamp64/www/' and unzip Git source file here.
5. Give a folder name and start Wamp Server. 
6. Open any browser and try to open http://127.0.0.1/what-your-folder-name/


Kindly feel free to share your queries... :)

**Comment by halimjr** [comment]
Hello @neerajsinghsonu 
I am able to run this script on a web server. Everything is working fine. But I want to get a new feature if possible.
Is there any way to get targeted user top 10 post URL with maximum likes?

**Pull request merged**
